# Generated by Django 5.2.4 on 2025-10-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='route',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='time',
        ),
        migrations.AddField(
            model_name='route',
            name='arrival_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='available_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='bus_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='bus_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='route',
            name='departure_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='total_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
