# Generated by Django 5.2.4 on 2025-10-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_route_bus_remove_route_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='total_seats',
        ),
    ]
